# Change these first
owner: SebaYB # Your GitHub organization or username, where this repository lives
repo: HaworthStatusPage # The name of this repository

sites:
  - name: Haworth Landing Page
    url: https://haworth-rp.com
  - name: Haworth Foro
    url: https://foro.haworth-rp.com
  - name: Haworth Foro Law
    url: https://law.haworth-rp.com
  - name: Servidor de SA-MP (US-RP test)
    url: https://www.open.mp/servers/37.230.137.174:7777
  - name: Test Broken Site
    url: https://thissitedoesnotexist.koj.co
    
assignees:
  - SebaYB

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /HaworthStatusPage
  logoUrl: https://media.discordapp.net/attachments/1069721282435883119/1072015861617012756/falklandstrazo.png?width=325&height=325
  name: Haworth Roleplay
  introTitle: "En **Haworth** Status podrás ver el estado de nuestros servidores."
  introMessage: Los estados están en **tiempo real**.
  navbar:
    - title: Haworth Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
