# Change these first
owner: SebaYB # Your GitHub organization or username, where this repository lives
repo: HaworthStatusPage # The name of this repository

sites:
  - name: Haworth Landing Page
    url: https://haworth-rp.com
  - name: Haworth Foro
    url: https://foro.haworth-rp.com
  - name: Haworth Foro Law
    url: https://law.haworth-rp.com
  - name: Servidor de SA-MP (US-RP test)
    url: https://www.open.mp/servers/37.230.137.174:7777
  - name: Test Broken Site
    url: https://thissitedoesnotexist.koj.co
    
assignees:
  - SebaYB

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /HaworthStatusPage
  logoUrl: https://media.discordapp.net/attachments/1069721282435883119/1072015861617012756/falklandstrazo.png?width=325&height=325
  name: Haworth Roleplay
  introTitle: "En **Haworth** Status podrás ver el estado de nuestros servidores."
  introMessage: Los estados están en **tiempo real**.
  navbar:
    - title: Haworth Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration

i18n: 
  activeIncidents: Incidentes activos
  allSystemsOperational: Todos los sistemas funcionan correctamente
  incidentReport: "Incidente #$NUMBER →"
  activeIncidentSummary: Abierto el $DATE con $POSTS posts
  incidentTitle: Detalles del incidente $NUMBER 
  incidentDetails: Detalles del incidente
  incidentFixed: Arreglado
  incidentOngoing: En curso
  incidentOpenedAt: Abierto a las
  incidentClosedAt: Cerrado a las
  incidentViewOnGitHub: Ver y suscribirse en GitHub
  incidentCommentSummary: Posted el $DATE por $AUTHOR
  incidentBack: ← Volver a todos los incidentes
  pastIncidents: Incidentes pasados
  pastIncidentsResolved: Resuelto en $MINUTES minutos con $POSTS posts
  liveStatus: Estado en tiempo real
  overallUptime: "Tiempo de actividad general: $UPTIME"
  overallUptimeTitle: Tiempo de actividad general
  averageResponseTime: "Average response time: $TIMEms"
  averageResponseTimeTitle: Respuesta promedio
  sevelDayResponseTime: Tiempo de respuesta en los últimos 7 días
  responseTimeMs: Tiempo de respuesta (ms)
  up: Encendido
  down: Apagado
  degraded: Degraded
  ms: ms
  loading: Cargando
  navGitHub: GitHub
  footer: This page is [open source]($REPO), powered by [Upptime](https://upptime.js.org)
  rateLimitExceededTitle: Rate limit exceeded
  rateLimitExceededIntro: You have exceeded the number of requests you can do in an hour, so you'll have to wait before accessing this website again. Alternately, you can add a GitHub Personal Access Token to continue to use this website.
  rateLimitExceededWhatDoesErrorMean: What does this error mean?
  rateLimitExceededErrorMeaning: This website uses the GitHub API to access real-time data about our websites' status. By default, GitHub allows each IP address 60 requests per hour, which you have consumed.
  rateLimitExceededErrorHowCanFix: How can I fix it?
  rateLimitExceededErrorFix: You can wait for another hour and your IP address' limit will be restored. Alternately, you can add your GitHub Personal Access Token, which gives you an additional 5,000 requests per hour.
  rateLimitExceededGeneratePAT: Learn how to generate a Personal Access Token
  rateLimitExceededHasSet: You have a personal access token set.
  rateLimitExceededRemoveToken: Remove token
  rateLimitExceededGitHubPAT: GitHub Personal Access Token
  rateLimitExceededCopyPastePAT: Copy and paste your token
  rateLimitExceededSaveToken: Save token
  errorTitle: An error occurred
  errorIntro: An error occurred in trying to get the latest status details.
  errorText: You can try again in a few moments.
  errorHome: Go to the homepage
  pastScheduledMaintenance: Past Scheduled Maintenance
  scheduledMaintenance: Scheduled Maintenance
  scheduledMaintenanceSummaryStarted: Started at $DATE for $DURATION minutes
  scheduledMaintenanceSummaryStarts: Starts at $DATE for $DURATION minutes
  startedAt: Started at
  startsAt: Starts at
  duration: Duration
  durationMin: $DURATION minutes
  incidentCompleted: Completed
  incidentScheduled: Scheduled
  duration24H: 24h
  duration7D: 7d
  duration30D: 30d
  duration1Y: 1y
  durationAll: 
