# Change these first
owner: SebaYB # Your GitHub organization or username, where this repository lives
repo: HaworthStatusPage # The name of this repository

sites:
  - name: Haworth Landing Page
    url: https://haworth-rp.com
  - name: Haworth Foro
    url: https://foro.haworth-rp.com
  - name: Haworth Foro Law
    url: https://law.haworth-rp.com
  - name: Test
   # url: https://sampmonitoring.com/396/
    url: https://sebayb.github.io/HaworthStatusPage
    
assignees:
  - SebaYB

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  apiBaseUrl: https://api.github.com
  theme: ocean
  baseUrl: /HaworthStatusPage
  logoUrl: https://media.discordapp.net/attachments/1069721282435883119/1072015861617012756/falklandstrazo.png?width=325&height=325
  name: Haworth Roleplay
  introTitle: "En **Haworth** Status podrás ver el estado de nuestros servidores."
  introMessage: Los estados están en **tiempo real**.
  navbar:
    - title: Haworth Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: Discord
      href: https://discord.com/invite/haworth/

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration

# Traducción
i18n: 
  activeIncidents: Incidentes activos
  allSystemsOperational: Todos los sistemas funcionan correctamente
  degradedPerformance:  Rendimiento degradado
  completeOutage: Apagado completo
  partialOutage: Interrupción parcial
  incidentReport: "Incidente #$NUMBER →"
  activeIncidentSummary: Abierto el $DATE con $POSTS posts
  incidentTitle: Detalles del incidente $NUMBER 
  incidentDetails: Detalles del incidente
  incidentFixed: Arreglado
  incidentOngoing: En curso
  incidentOpenedAt: Abierto a las
  incidentClosedAt: Cerrado a las
  incidentViewOnGitHub: Ver y suscribirse en GitHub
  incidentCommentSummary: Posted el $DATE por $AUTHOR
  incidentBack: ← Volver a todos los incidentes
  pastIncidents: Incidentes pasados
  pastIncidentsResolved: Resuelto en $MINUTES minutos con $POSTS posts
  liveStatus: Estado en tiempo real
  overallUptime: "Tiempo de actividad general: $UPTIME"
  overallUptimeTitle: Tiempo de actividad general
  averageResponseTime: "Tiempo de respuesta promedio: $TIMEms"
  averageResponseTimeTitle: Respuesta promedio
  sevelDayResponseTime: Tiempo de respuesta en los últimos 7 días
  responseTimeMs: Tiempo de respuesta (ms)
  up: Encendido
  down: Apagado
  degraded: Degraded
  ms: ms
  loading: Cargando
  navGitHub: GitHub
  footer: Powered by [Upptime](https://upptime.js.org)
  rateLimitExceededTitle: Excede el límite de velocidad
  rateLimitExceededIntro: Ha superado el número de solicitudes que puede realizar en una hora, por lo que tendrá que esperar antes de volver a acceder a este sitio web. Alternativamente, puede agregar un token de acceso personal de GitHub para continuar usando este sitio web.
  rateLimitExceededWhatDoesErrorMean: ¿Qué significa este error?
  rateLimitExceededErrorMeaning: Este sitio web utiliza la API de GitHub para acceder a datos en tiempo real sobre el estado de nuestros sitios web. De manera predeterminada, GitHub permite que cada dirección IP realice 60 solicitudes por hora, las que ha consumido.
  rateLimitExceededErrorHowCanFix: ¿Cómo puedo arreglarlo?
  rateLimitExceededErrorFix: Puede esperar otra hora y se restablecerá el límite de su dirección IP. Como alternativa, puede agregar su token de acceso personal de GitHub, que le brinda 5000 solicitudes adicionales por hora.
  rateLimitExceededGeneratePAT: Aprenda a generar un Personal Access Token.
  rateLimitExceededHasSet: Ya tienes un Personal Access Token colocado.
  rateLimitExceededRemoveToken: Eliminar token
  rateLimitExceededGitHubPAT: GitHub Personal Access Token
  rateLimitExceededCopyPastePAT: Copia y pega tu token
  rateLimitExceededSaveToken: Guardar token
  errorTitle: Ha ocurrido un error
  errorIntro: Se produjo un error al intentar obtener los detalles de estado más recientes.
  errorText: Puedes volver a intentarlo en unos momentos.
  errorHome: Ir al inicio
  pastScheduledMaintenance: Mantenimiento programado pasado
  scheduledMaintenance: Mantenimiento programado
  scheduledMaintenanceSummaryStarted: Iniciado el $DATE por $DURATION minutos
  scheduledMaintenanceSummaryStarts: Inicia el $DATE por $DURATION minutos
  startedAt: Iniciado el
  startsAt: Inicia el
  duration: Duración
  durationMin: $DURATION minutos
  incidentCompleted: Completado
  incidentScheduled: Programado
  duration24H: 24h
  duration7D: 7d
  duration30D: 30d
  duration1Y: 1y
  durationAll: todo
  
  # Adicionales
  user-agent: SebaYB
  
  # Tema
  
